-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 15:28:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema i-garden
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema i-garden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `i-garden` DEFAULT CHARACTER SET utf8 ;
USE `i-garden` ;

-- -----------------------------------------------------
-- Table `i-garden`.`caracteristique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`caracteristique` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`caracteristique` (
  `id_caracteristique` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `type_sol` VARCHAR(15) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_caracteristique`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`cycle_vegetatif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`cycle_vegetatif` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`cycle_vegetatif` (
  `id_cycle_vegetatif` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_cycle_vegetatif`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`etat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`etat` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`etat` (
  `id_etat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_etat`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`famille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`famille` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`famille` (
  `id_famille` INT NOT NULL AUTO_INCREMENT,
  `id_famille_parente` INT NULL DEFAULT NULL,
  `nom_famille` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_famille`),
  INDEX `nom_famille_UNIQUE` (`nom_famille` ASC) VISIBLE,
  INDEX `id_famille_parente_idx` (`id_famille_parente` ASC) VISIBLE,
  CONSTRAINT `id_famille_parente`
    FOREIGN KEY (`id_famille_parente`)
    REFERENCES `i-garden`.`famille` (`id_famille`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`graine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`graine` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`graine` (
  `id_graine` INT NOT NULL AUTO_INCREMENT,
  `id_famille` INT NULL DEFAULT NULL,
  `nom` VARCHAR(30) NOT NULL,
  `nom_latin` VARCHAR(50) NULL DEFAULT NULL,
  `classification` ENUM('Vivace', 'Annuelle', 'Bisannuelle') NOT NULL,
  `hauteur_max` INT NULL DEFAULT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `icone` VARCHAR(255) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_graine`),
  INDEX `id_famille_idx` (`id_famille` ASC) VISIBLE,
  CONSTRAINT `id_famille`
    FOREIGN KEY (`id_famille`)
    REFERENCES `i-garden`.`famille` (`id_famille`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`rusticite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`rusticite` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`rusticite` (
  `id_rusticite` INT NOT NULL AUTO_INCREMENT,
  `code_rusticite` VARCHAR(2) NOT NULL,
  `temp_min` DECIMAL(2,1) NOT NULL,
  `temp_max` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`id_rusticite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`jardin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`jardin` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`jardin` (
  `id_jardin` INT NOT NULL AUTO_INCREMENT,
  `id_rusticite` INT NULL DEFAULT NULL,
  `nom_jardin` VARCHAR(30) NOT NULL,
  `code_postal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_jardin`),
  INDEX `id_rusticite_idx` (`id_rusticite` ASC) VISIBLE,
  CONSTRAINT `id_rusticite`
    FOREIGN KEY (`id_rusticite`)
    REFERENCES `i-garden`.`rusticite` (`id_rusticite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`zone` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`zone` (
  `id_zone` INT NOT NULL AUTO_INCREMENT,
  `id_jardin_zone` INT NOT NULL,
  `id_caracteristique` INT NULL DEFAULT NULL,
  `id_rusticite_zone` INT NULL DEFAULT NULL,
  `nom` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_zone`),
  INDEX `id_jardin_idx` (`id_jardin_zone` ASC) VISIBLE,
  INDEX `id_caracteristique_idx` (`id_caracteristique` ASC) VISIBLE,
  INDEX `id_rusticite_idx` (`id_rusticite_zone` ASC) VISIBLE,
  CONSTRAINT `id_caracteristique`
    FOREIGN KEY (`id_caracteristique`)
    REFERENCES `i-garden`.`caracteristique` (`id_caracteristique`),
  CONSTRAINT `id_jardin_zone`
    FOREIGN KEY (`id_jardin_zone`)
    REFERENCES `i-garden`.`jardin` (`id_jardin`)
    ON DELETE CASCADE,
  CONSTRAINT `id_rusticite_zone`
    FOREIGN KEY (`id_rusticite_zone`)
    REFERENCES `i-garden`.`rusticite` (`id_rusticite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`plante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`plante` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`plante` (
  `id_plante` INT NOT NULL AUTO_INCREMENT,
  `id_graine` INT NOT NULL,
  `id_jardin_pousser` INT NOT NULL,
  `id_zone` INT NULL DEFAULT NULL,
  `id_cycle_vegetatif` INT NOT NULL,
  `date_semis` DATE NULL DEFAULT NULL,
  `date_repiquage` DATE NULL DEFAULT NULL,
  `date_floraison` DATE NULL DEFAULT NULL,
  `date_recolte` DATE NULL DEFAULT NULL,
  `quantite_recolte` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_plante`),
  INDEX `id_graine_idx` (`id_graine` ASC) VISIBLE,
  INDEX `id_jardin_idx` (`id_jardin_pousser` ASC) VISIBLE,
  INDEX `id_zone_idx` (`id_zone` ASC) VISIBLE,
  INDEX `id_cycle_vegetatif_idx` (`id_cycle_vegetatif` ASC) VISIBLE,
  CONSTRAINT `id_cycle_vegetatif`
    FOREIGN KEY (`id_cycle_vegetatif`)
    REFERENCES `i-garden`.`cycle_vegetatif` (`id_cycle_vegetatif`),
  CONSTRAINT `id_graine`
    FOREIGN KEY (`id_graine`)
    REFERENCES `i-garden`.`graine` (`id_graine`),
  CONSTRAINT `id_jardin_pousser`
    FOREIGN KEY (`id_jardin_pousser`)
    REFERENCES `i-garden`.`jardin` (`id_jardin`)
    ON DELETE CASCADE,
  CONSTRAINT `id_zone`
    FOREIGN KEY (`id_zone`)
    REFERENCES `i-garden`.`zone` (`id_zone`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`etat_plante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`etat_plante` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`etat_plante` (
  `id_plante` INT NOT NULL,
  `id_etat` INT NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `status` ENUM('Actif', 'Passé', 'Traité') NOT NULL DEFAULT 'Actif',
  PRIMARY KEY (`id_plante`, `id_etat`),
  INDEX `id_etat_idx` (`id_etat` ASC) VISIBLE,
  CONSTRAINT `id_etat`
    FOREIGN KEY (`id_etat`)
    REFERENCES `i-garden`.`etat` (`id_etat`)
    ON DELETE CASCADE,
  CONSTRAINT `id_plante`
    FOREIGN KEY (`id_plante`)
    REFERENCES `i-garden`.`plante` (`id_plante`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`historique_cycle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`historique_cycle` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`historique_cycle` (
  `id_cycle_vegetatif_archive` INT NOT NULL,
  `id_plante_histo_cycle` INT NOT NULL,
  `date_changement` DATETIME NOT NULL,
  `nom` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_cycle_vegetatif_archive`, `id_plante_histo_cycle`),
  INDEX `id_plante_idx` (`id_plante_histo_cycle` ASC) VISIBLE,
  CONSTRAINT `id_cycle_vegetatif_archive`
    FOREIGN KEY (`id_cycle_vegetatif_archive`)
    REFERENCES `i-garden`.`cycle_vegetatif` (`id_cycle_vegetatif`)
    ON DELETE CASCADE,
  CONSTRAINT `id_plante_histo_cycle`
    FOREIGN KEY (`id_plante_histo_cycle`)
    REFERENCES `i-garden`.`plante` (`id_plante`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`historique_etat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`historique_etat` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`historique_etat` (
  `id_etat_archive` INT NOT NULL,
  `id_plante_archive` INT NOT NULL,
  `date_changement` DATETIME NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `status` ENUM('Actif', 'Passé', 'Traité') NOT NULL,
  PRIMARY KEY (`id_etat_archive`, `id_plante_archive`),
  INDEX `id_plante_idx` (`id_plante_archive` ASC) VISIBLE,
  CONSTRAINT `id_etat_archive`
    FOREIGN KEY (`id_etat_archive`)
    REFERENCES `i-garden`.`etat` (`id_etat`)
    ON DELETE CASCADE,
  CONSTRAINT `id_plante_archive`
    FOREIGN KEY (`id_plante_archive`)
    REFERENCES `i-garden`.`plante` (`id_plante`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`historique_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`historique_zone` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`historique_zone` (
  `id_plante_zone` INT NOT NULL,
  `id_zone_histo` INT NOT NULL,
  `date_changement` DATETIME NOT NULL,
  PRIMARY KEY (`id_plante_zone`, `id_zone_histo`),
  INDEX `id_zone_idx` (`id_zone_histo` ASC) VISIBLE,
  CONSTRAINT `id_plante_zone`
    FOREIGN KEY (`id_plante_zone`)
    REFERENCES `i-garden`.`plante` (`id_plante`)
    ON DELETE CASCADE,
  CONSTRAINT `id_zone_histo`
    FOREIGN KEY (`id_zone_histo`)
    REFERENCES `i-garden`.`zone` (`id_zone`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `mot_de_passe` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `i-garden`.`jardin_utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`jardin_utilisateur` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`jardin_utilisateur` (
  `id_utilisateur` INT NOT NULL,
  `id_jardin` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`, `id_jardin`),
  INDEX `id_jardin_idx` (`id_jardin` ASC) VISIBLE,
  CONSTRAINT `id_jardin`
    FOREIGN KEY (`id_jardin`)
    REFERENCES `i-garden`.`jardin` (`id_jardin`)
    ON DELETE CASCADE,
  CONSTRAINT `id_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `i-garden`.`utilisateur` (`id_utilisateur`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
