-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 14:50:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema i-garden
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema i-garden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `i-garden` DEFAULT CHARACTER SET utf8 ;
USE `i-garden` ;

-- -----------------------------------------------------
-- Table `i-garden`.`ETAT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`ETAT` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`ETAT` (
  `id_etat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_etat`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`CARACTERISTIQUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`CARACTERISTIQUE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`CARACTERISTIQUE` (
  `id_caracteristique` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `type_sol` VARCHAR(15) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id_caracteristique`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`RUSTICITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`RUSTICITE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`RUSTICITE` (
  `id_rusticite` INT NOT NULL AUTO_INCREMENT,
  `code_rusticite` VARCHAR(2) NOT NULL,
  `temp_min` DECIMAL(2,1) NOT NULL,
  `temp_max` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`id_rusticite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`UTILISATEUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`UTILISATEUR` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`UTILISATEUR` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `mot_de_passe` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`JARDIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`JARDIN` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`JARDIN` (
  `id_jardin` INT NOT NULL AUTO_INCREMENT,
  `id_rusticite` INT NULL,
  `nom_jardin` VARCHAR(30) NOT NULL,
  `code_postal` INT(5) NULL,
  PRIMARY KEY (`id_jardin`),
  INDEX `id_rusticite_idx` (`id_rusticite` ASC) VISIBLE,
  CONSTRAINT `id_rusticite`
    FOREIGN KEY (`id_rusticite`)
    REFERENCES `i-garden`.`RUSTICITE` (`id_rusticite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`JARDIN_UTILISATEUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`JARDIN_UTILISATEUR` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`JARDIN_UTILISATEUR` (
  `id_utilisateur` INT NOT NULL,
  `id_jardin` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`, `id_jardin`),
  INDEX `id_jardin_idx` (`id_jardin` ASC) VISIBLE,
  CONSTRAINT `id_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `i-garden`.`UTILISATEUR` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_jardin`
    FOREIGN KEY (`id_jardin`)
    REFERENCES `i-garden`.`JARDIN` (`id_jardin`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`ZONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`ZONE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`ZONE` (
  `id_zone` INT NOT NULL AUTO_INCREMENT,
  `id_jardin` INT NOT NULL,
  `id_caracteristique` INT NULL,
  `id_rusticite` INT NULL,
  `nom` VARCHAR(30) NULL,
  PRIMARY KEY (`id_zone`),
  INDEX `id_jardin_idx` (`id_jardin` ASC) VISIBLE,
  INDEX `id_caracteristique_idx` (`id_caracteristique` ASC) VISIBLE,
  INDEX `id_rusticite_idx` (`id_rusticite` ASC) VISIBLE,
  CONSTRAINT `id_jardin`
    FOREIGN KEY (`id_jardin`)
    REFERENCES `i-garden`.`JARDIN` (`id_jardin`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_caracteristique`
    FOREIGN KEY (`id_caracteristique`)
    REFERENCES `i-garden`.`CARACTERISTIQUE` (`id_caracteristique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_rusticite`
    FOREIGN KEY (`id_rusticite`)
    REFERENCES `i-garden`.`RUSTICITE` (`id_rusticite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`FAMILLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`FAMILLE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`FAMILLE` (
  `id_famille` INT NOT NULL AUTO_INCREMENT,
  `id_famille_parente` INT NULL,
  `nom_famille` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_famille`),
  INDEX `nom_famille_UNIQUE` (`nom_famille` ASC) VISIBLE,
  INDEX `id_famille_parente_idx` (`id_famille_parente` ASC) VISIBLE,
  CONSTRAINT `id_famille_parente`
    FOREIGN KEY (`id_famille_parente`)
    REFERENCES `i-garden`.`FAMILLE` (`id_famille`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`GRAINE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`GRAINE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`GRAINE` (
  `id_graine` INT NOT NULL AUTO_INCREMENT,
  `id_famille` INT NULL,
  `nom` VARCHAR(30) NOT NULL,
  `nom_latin` VARCHAR(50) NULL,
  `classification` ENUM('Vivace', 'Annuelle', 'Bisannuelle') NOT NULL,
  `hauteur_max` INT NULL,
  `photo` VARCHAR(255) NULL,
  `icone` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id_graine`),
  INDEX `id_famille_idx` (`id_famille` ASC) VISIBLE,
  CONSTRAINT `id_famille`
    FOREIGN KEY (`id_famille`)
    REFERENCES `i-garden`.`FAMILLE` (`id_famille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`CYCLE_VEGETATIF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`CYCLE_VEGETATIF` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`CYCLE_VEGETATIF` (
  `id_cycle_vegetatif` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_cycle_vegetatif`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`PLANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`PLANTE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`PLANTE` (
  `id_plante` INT NOT NULL AUTO_INCREMENT,
  `id_graine` INT NOT NULL,
  `id_jardin` INT NOT NULL,
  `id_zone` INT NULL,
  `id_cycle_vegetatif` INT NOT NULL,
  `date_semis` DATE NULL,
  `date_repiquage` DATE NULL,
  `date_floraison` DATE NULL,
  `date_recolte` DATE NULL,
  `quantite_recolte` INT NULL,
  PRIMARY KEY (`id_plante`),
  INDEX `id_graine_idx` (`id_graine` ASC) VISIBLE,
  INDEX `id_jardin_idx` (`id_jardin` ASC) VISIBLE,
  INDEX `id_zone_idx` (`id_zone` ASC) VISIBLE,
  INDEX `id_cycle_vegetatif_idx` (`id_cycle_vegetatif` ASC) VISIBLE,
  CONSTRAINT `id_graine`
    FOREIGN KEY (`id_graine`)
    REFERENCES `i-garden`.`GRAINE` (`id_graine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_jardin`
    FOREIGN KEY (`id_jardin`)
    REFERENCES `i-garden`.`JARDIN` (`id_jardin`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_zone`
    FOREIGN KEY (`id_zone`)
    REFERENCES `i-garden`.`ZONE` (`id_zone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cycle_vegetatif`
    FOREIGN KEY (`id_cycle_vegetatif`)
    REFERENCES `i-garden`.`CYCLE_VEGETATIF` (`id_cycle_vegetatif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`HISTORIQUE_ZONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`HISTORIQUE_ZONE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`HISTORIQUE_ZONE` (
  `id_plante` INT NOT NULL,
  `id_zone` INT NOT NULL,
  `date_changement` DATETIME NOT NULL,
  PRIMARY KEY (`id_plante`, `id_zone`),
  INDEX `id_zone_idx` (`id_zone` ASC) VISIBLE,
  CONSTRAINT `id_plante`
    FOREIGN KEY (`id_plante`)
    REFERENCES `i-garden`.`PLANTE` (`id_plante`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_zone`
    FOREIGN KEY (`id_zone`)
    REFERENCES `i-garden`.`ZONE` (`id_zone`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`ETAT_PLANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`ETAT_PLANTE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`ETAT_PLANTE` (
  `id_plante` INT NOT NULL,
  `id_etat` INT NOT NULL,
  `date` DATETIME NULL,
  `status` ENUM('Actif', 'Passé', 'Traité') NOT NULL DEFAULT 'Actif',
  PRIMARY KEY (`id_plante`, `id_etat`),
  INDEX `id_etat_idx` (`id_etat` ASC) VISIBLE,
  CONSTRAINT `id_plante`
    FOREIGN KEY (`id_plante`)
    REFERENCES `i-garden`.`PLANTE` (`id_plante`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_etat`
    FOREIGN KEY (`id_etat`)
    REFERENCES `i-garden`.`ETAT` (`id_etat`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`HISTORIQUE_CYCLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`HISTORIQUE_CYCLE` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`HISTORIQUE_CYCLE` (
  `id_cycle_vegetatif` INT NOT NULL,
  `id_plante` INT NOT NULL,
  `date_changement` DATETIME NOT NULL,
  `nom` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_cycle_vegetatif`, `id_plante`),
  INDEX `id_plante_idx` (`id_plante` ASC) VISIBLE,
  CONSTRAINT `id_cycle_vegetatif`
    FOREIGN KEY (`id_cycle_vegetatif`)
    REFERENCES `i-garden`.`CYCLE_VEGETATIF` (`id_cycle_vegetatif`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_plante`
    FOREIGN KEY (`id_plante`)
    REFERENCES `i-garden`.`PLANTE` (`id_plante`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `i-garden`.`HISTORIQUE_ETAT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `i-garden`.`HISTORIQUE_ETAT` ;

CREATE TABLE IF NOT EXISTS `i-garden`.`HISTORIQUE_ETAT` (
  `id_etat` INT NOT NULL,
  `id_plante` INT NOT NULL,
  `date_changement` DATETIME NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `date` DATE NULL,
  `status` ENUM('Actif', 'Passé', 'Traité') NOT NULL,
  PRIMARY KEY (`id_etat`, `id_plante`),
  INDEX `id_plante_idx` (`id_plante` ASC) VISIBLE,
  CONSTRAINT `id_etat`
    FOREIGN KEY (`id_etat`)
    REFERENCES `i-garden`.`ETAT` (`id_etat`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_plante`
    FOREIGN KEY (`id_plante`)
    REFERENCES `i-garden`.`PLANTE` (`id_plante`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
